language: java

jdk:
  - oraclejdk8

addons:
  firefox: latest

cache:
  directories:
    - $HOME/.m2

install: /bin/true

script: ./mvnw verify -B -Djava.util.logging.config.file="src/test/resources/logging.properties"

after_success:
  - bash <(curl -s https://codecov.io/bash)
