/*
 * This file is generated by jOOQ.
*/
package de.vorb.platon.persistence.jooq.tables.records;


import de.vorb.platon.persistence.jooq.tables.CommentThread;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentThreadRecord extends UpdatableRecordImpl<CommentThreadRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 542597670;

    /**
     * Setter for <code>public.comment_thread.id</code>.
     */
    public CommentThreadRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.comment_thread.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.comment_thread.url</code>.
     */
    public CommentThreadRecord setUrl(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.comment_thread.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.comment_thread.title</code>.
     */
    public CommentThreadRecord setTitle(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.comment_thread.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CommentThread.COMMENT_THREAD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CommentThread.COMMENT_THREAD.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CommentThread.COMMENT_THREAD.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentThreadRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentThreadRecord value2(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentThreadRecord value3(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentThreadRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommentThreadRecord
     */
    public CommentThreadRecord() {
        super(CommentThread.COMMENT_THREAD);
    }

    /**
     * Create a detached, initialised CommentThreadRecord
     */
    public CommentThreadRecord(Long id, String url, String title) {
        super(CommentThread.COMMENT_THREAD);

        set(0, id);
        set(1, url);
        set(2, title);
    }
}
