/*
 * This file is generated by jOOQ.
*/
package de.vorb.platon.persistence.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentThread implements Serializable {

    private static final long serialVersionUID = 1625604914;

    private Long   id;
    private String url;
    private String title;

    public CommentThread() {}

    public CommentThread(CommentThread value) {
        this.id = value.id;
        this.url = value.url;
        this.title = value.title;
    }

    public CommentThread(
        Long   id,
        String url,
        String title
    ) {
        this.id = id;
        this.url = url;
        this.title = title;
    }

    public Long getId() {
        return this.id;
    }

    public CommentThread setId(Long id) {
        this.id = id;
        return this;
    }

    public String getUrl() {
        return this.url;
    }

    public CommentThread setUrl(String url) {
        this.url = url;
        return this;
    }

    public String getTitle() {
        return this.title;
    }

    public CommentThread setTitle(String title) {
        this.title = title;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CommentThread (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(title);

        sb.append(")");
        return sb.toString();
    }
}
