/*
 * This file is generated by jOOQ.
*/
package de.vorb.platon.persistence.jooq.tables.pojos;


import de.vorb.platon.model.CommentStatus;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comment implements Serializable {

    private static final long serialVersionUID = -1369366847;

    private Long          id;
    private Long          threadId;
    private Long          parentId;
    private LocalDateTime creationDate;
    private LocalDateTime lastModificationDate;
    private CommentStatus status;
    private String        text;
    private String        author;
    private String        url;
    private byte[]        authorHash;

    public Comment() {}

    public Comment(Comment value) {
        this.id = value.id;
        this.threadId = value.threadId;
        this.parentId = value.parentId;
        this.creationDate = value.creationDate;
        this.lastModificationDate = value.lastModificationDate;
        this.status = value.status;
        this.text = value.text;
        this.author = value.author;
        this.url = value.url;
        this.authorHash = value.authorHash;
    }

    public Comment(
        Long          id,
        Long          threadId,
        Long          parentId,
        LocalDateTime creationDate,
        LocalDateTime lastModificationDate,
        CommentStatus status,
        String        text,
        String        author,
        String        url,
        byte[]        authorHash
    ) {
        this.id = id;
        this.threadId = threadId;
        this.parentId = parentId;
        this.creationDate = creationDate;
        this.lastModificationDate = lastModificationDate;
        this.status = status;
        this.text = text;
        this.author = author;
        this.url = url;
        this.authorHash = authorHash;
    }

    public Long getId() {
        return this.id;
    }

    public Comment setId(Long id) {
        this.id = id;
        return this;
    }

    public Long getThreadId() {
        return this.threadId;
    }

    public Comment setThreadId(Long threadId) {
        this.threadId = threadId;
        return this;
    }

    public Long getParentId() {
        return this.parentId;
    }

    public Comment setParentId(Long parentId) {
        this.parentId = parentId;
        return this;
    }

    public LocalDateTime getCreationDate() {
        return this.creationDate;
    }

    public Comment setCreationDate(LocalDateTime creationDate) {
        this.creationDate = creationDate;
        return this;
    }

    public LocalDateTime getLastModificationDate() {
        return this.lastModificationDate;
    }

    public Comment setLastModificationDate(LocalDateTime lastModificationDate) {
        this.lastModificationDate = lastModificationDate;
        return this;
    }

    public CommentStatus getStatus() {
        return this.status;
    }

    public Comment setStatus(CommentStatus status) {
        this.status = status;
        return this;
    }

    public String getText() {
        return this.text;
    }

    public Comment setText(String text) {
        this.text = text;
        return this;
    }

    public String getAuthor() {
        return this.author;
    }

    public Comment setAuthor(String author) {
        this.author = author;
        return this;
    }

    public String getUrl() {
        return this.url;
    }

    public Comment setUrl(String url) {
        this.url = url;
        return this;
    }

    public byte[] getAuthorHash() {
        return this.authorHash;
    }

    public Comment setAuthorHash(byte... authorHash) {
        this.authorHash = authorHash;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Comment (");

        sb.append(id);
        sb.append(", ").append(threadId);
        sb.append(", ").append(parentId);
        sb.append(", ").append(creationDate);
        sb.append(", ").append(lastModificationDate);
        sb.append(", ").append(status);
        sb.append(", ").append(text);
        sb.append(", ").append(author);
        sb.append(", ").append(url);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
