/*
 * This file is generated by jOOQ.
*/
package de.vorb.platon.persistence.jooq;


import de.vorb.platon.persistence.jooq.tables.Comment;
import de.vorb.platon.persistence.jooq.tables.CommentThread;
import de.vorb.platon.persistence.jooq.tables.Property;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COMMENT_PKEY = Indexes0.COMMENT_PKEY;
    public static final Index IDX__COMMENT__CREATION_DATE = Indexes0.IDX__COMMENT__CREATION_DATE;
    public static final Index IDX__COMMENT__STATUS = Indexes0.IDX__COMMENT__STATUS;
    public static final Index IDX__COMMENT__THREAD_ID = Indexes0.IDX__COMMENT__THREAD_ID;
    public static final Index COMMENT_THREAD_PKEY = Indexes0.COMMENT_THREAD_PKEY;
    public static final Index COMMENT_THREAD_URL_KEY = Indexes0.COMMENT_THREAD_URL_KEY;
    public static final Index PROPERTY_PKEY = Indexes0.PROPERTY_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index COMMENT_PKEY = Internal.createIndex("comment_pkey", Comment.COMMENT, new OrderField[] { Comment.COMMENT.ID }, true);
        public static Index IDX__COMMENT__CREATION_DATE = Internal.createIndex("idx__comment__creation_date", Comment.COMMENT, new OrderField[] { Comment.COMMENT.CREATION_DATE }, false);
        public static Index IDX__COMMENT__STATUS = Internal.createIndex("idx__comment__status", Comment.COMMENT, new OrderField[] { Comment.COMMENT.STATUS }, false);
        public static Index IDX__COMMENT__THREAD_ID = Internal.createIndex("idx__comment__thread_id", Comment.COMMENT, new OrderField[] { Comment.COMMENT.THREAD_ID }, false);
        public static Index COMMENT_THREAD_PKEY = Internal.createIndex("comment_thread_pkey", CommentThread.COMMENT_THREAD, new OrderField[] { CommentThread.COMMENT_THREAD.ID }, true);
        public static Index COMMENT_THREAD_URL_KEY = Internal.createIndex("comment_thread_url_key", CommentThread.COMMENT_THREAD, new OrderField[] { CommentThread.COMMENT_THREAD.URL }, true);
        public static Index PROPERTY_PKEY = Internal.createIndex("property_pkey", Property.PROPERTY, new OrderField[] { Property.PROPERTY.KEY }, true);
    }
}
