/*
 * This file is generated by jOOQ.
*/
package de.vorb.platon.persistence.jooq;


import de.vorb.platon.persistence.jooq.tables.Comment;
import de.vorb.platon.persistence.jooq.tables.CommentThread;
import de.vorb.platon.persistence.jooq.tables.Property;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -2087980905;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.comment</code>.
     */
    public final Comment COMMENT = de.vorb.platon.persistence.jooq.tables.Comment.COMMENT;

    /**
     * The table <code>public.comment_thread</code>.
     */
    public final CommentThread COMMENT_THREAD = de.vorb.platon.persistence.jooq.tables.CommentThread.COMMENT_THREAD;

    /**
     * The table <code>public.property</code>.
     */
    public final Property PROPERTY = de.vorb.platon.persistence.jooq.tables.Property.PROPERTY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.COMMENT_ID_SEQ,
            Sequences.COMMENT_THREAD_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Comment.COMMENT,
            CommentThread.COMMENT_THREAD,
            Property.PROPERTY);
    }
}
