/*
 * This file is generated by jOOQ.
*/
package de.vorb.platon.persistence.jooq;


import de.vorb.platon.persistence.jooq.tables.Comment;
import de.vorb.platon.persistence.jooq.tables.CommentThread;
import de.vorb.platon.persistence.jooq.tables.Property;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.comment</code>.
     */
    public static final Comment COMMENT = de.vorb.platon.persistence.jooq.tables.Comment.COMMENT;

    /**
     * The table <code>public.comment_thread</code>.
     */
    public static final CommentThread COMMENT_THREAD = de.vorb.platon.persistence.jooq.tables.CommentThread.COMMENT_THREAD;

    /**
     * The table <code>public.property</code>.
     */
    public static final Property PROPERTY = de.vorb.platon.persistence.jooq.tables.Property.PROPERTY;
}
